FROM centos:centos7

ARG app_name

# base
RUN yum update -y && \
    yum install -y epel-release && \
    yum upgrade -y && \
    yum install -y wget && \
    yum install -y vi && \
    yum install -y htop && \
    yum install -y net-tools && \
    yum -y install wget which vim

# 環境
RUN echo 'TZ="Asia/Tokyo"' > /etc/sysconfig/clock
RUN cp /usr/share/zoneinfo/Asia/Tokyo /etc/localtime
RUN echo 'LANG="ja_JP.UTF-8"' > /etc/sysconfig/i18n
RUN echo 'LC_CTYPE="ja_JP.utf8"' >> /etc/sysconfig/i18n
RUN localedef -f UTF-8 -i ja_JP ja_JP.UTF-8


RUN yum install -y npm

RUN mkdir -p /var/www/lamp
RUN mkdir -p /var/log/mysql


RUN yum install -y httpd

RUN wget https://downloads.mariadb.com/MariaDB/mariadb_repo_setup
RUN bash mariadb_repo_setup --mariadb-server-version="mariadb-10.3"
RUN yum -y install MariaDB-server MariaDB-client
RUN chmod -R 777 /var/log/mysql

RUN yum -y install http://rpms.famillecollet.com/enterprise/remi-release-7.rpm
RUN yum -y install --enablerepo=remi-php73 php php-common php-opcache php-mbstring php-xdebug php-mysql php-mysqlnd php-zip php-pdo php-cli php-devel php-pear php-xml php-gd php-fpm
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
RUN php composer-setup.php
RUN php -r "unlink('composer-setup.php');"
RUN mv composer.phar /usr/local/bin/composer

RUN localedef -i ja_JP -c -f UTF-8 -A /usr/share/locale/locale.alias ja_JP.UTF-8
ENV LANG="ja_JP.UTF-8" \
    LANGUAGE="ja_JP:ja" \
    LC_ALL="ja_JP.UTF-8"

EXPOSE 80
EXPOSE 3306


